auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Looly's Blog 小磊的博客
url: http://www.xiaoleilu.com
feed: /atom.xml
author_info: <a href="http://xiaoleilu.com/">Looly</a>
